// Code generated by "stringer -type=ClientArchitecture"; DO NOT EDIT

package dhcp4

import "fmt"

const _ClientArchitecture_name = "ClientArchIntelX86"

var _ClientArchitecture_index = [...]uint8{0, 18}

func (i ClientArchitecture) String() string {
	if i >= ClientArchitecture(len(_ClientArchitecture_index)-1) {
		return fmt.Sprintf("ClientArchitecture(%d)", i)
	}
	return _ClientArchitecture_name[_ClientArchitecture_index[i]:_ClientArchitecture_index[i+1]]
}
