// Code generated by "stringer -type=MessageType"; DO NOT EDIT

package dhcp4

import "fmt"

const _MessageType_name = "Discover"

var _MessageType_index = [...]uint8{0, 8}

func (i MessageType) String() string {
	i -= 1
	if i >= MessageType(len(_MessageType_index)-1) {
		return fmt.Sprintf("MessageType(%d)", i+1)
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
